Ajout de la page blog
Virtual-Royaume/Royaume-Frontend pull request #44
Opened 2023-06-17 22:18 UTC by RomainSav

2023-06-18 14:46 UTC, Bluzzi commented on tailwind.config.ts
> +      links: "#69B0EB"
Plutôt `link` ?

2023-06-18 14:46 UTC, Bluzzi commented on src/lib/components/molecules/markdown/markdown.tsx
> +    <div>
Pour avoir un design système modulable, il faudrait qu'un maximum de nos composants extends leur composant vanilla.

Est-ce que tu pense qu'il y a un use-case ici si cette div extends la div vanilla pour avoir ses props ?

2023-06-18 20:00 UTC, Steellgold commented on tailwind.config.ts
> +      links: "#69B0EB"
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/44/commits/0c59f5aac857fb9eded7bd0c345f76134412a5b7

2023-06-19 14:13 UTC, Bluzzi requested changes

2023-06-19 14:13 UTC, Bluzzi commented on src/lib/components/molecules/content-table/content-table.tsx
> +    <div
Une `ContentTable` c'est un élément de navigation, donc l'utilisation d'une balise `nav` a du sens ici pour créer du contexte pour le SEO et l'accéssibilité.

2023-06-19 14:13 UTC, Bluzzi commented on test/blog/content-table.spec.ts
> +    const contentTable = page.getByLabel("content-table");
Comme dit plus, la `ContentTable` est un élément de navigation, donc ici on peux utiliser `page.getByRole("navigation", { name: "content-table" })`.

2023-06-19 14:13 UTC, Bluzzi commented on src/lib/components/molecules/content-table/content-table.tsx
> +        <div className="grid gap-1 pt-2" ref={itemsContainerRef}>
Pour une `ContentTable`, les éléments de navigation présent dedans ont un sens entre eux, il s'agit donc d'une liste et plus particulièrement dans ce cas une liste ordonnée. Donc pour chaque elements tu peux utiliser des `li` englobé dans un `ol`.

L'élément présent dans le `li` final peut-être un bouton ou un link.

2023-06-19 14:13 UTC, Bluzzi commented on test/blog/content-table.spec.ts
> +    await expect(ctButton).not.toBeDisabled();
Je ne suis pas sur de comprendre cette partie la, si on se situe actuellement sur la dernière partie du post, le bouton ne doit pas être désactivé ?

Sinon ça serait bien je pense d'avoir un check qui vérifie si :
- il y a bien eu un scroll
- le titre est bien dans le viewport

Mais actuellement je ne pense pas (ou du moins je ne sais pas) si ce genre de fonctionnalité existe sur Playwright.

2023-06-19 15:36 UTC, Bluzzi approved these changes

2023-06-19 15:36 UTC, Bluzzi commented on src/lib/components/molecules/markdown/elements/md-heading/md-heading.tsx
> +  return <h4 aria-label={text} className={clsx(styles, "mt-2")}>{text}</h4>;
Perplexe sur l'utilisation de `aria-label` ici, ça n'apporte pas un sens supplémentaire, juste le texte déjà présent. Côté accessibilité, l'utilisateur a déjà cette information via le texte en lui même.

2023-06-19 15:36 UTC, Bluzzi commented on test/blog/content-table.spec.ts
> +    await expect(titleSection).toBeInViewport();
Au top ahah 🎉

2023-06-19 15:36 UTC, Bluzzi commented
Je te laisse merge quand tu à check la review, tout est ok à par le dernier point sur l'utilisation des derniers `aria-label`.

2023-06-19 18:33 UTC, merged