Ajout des pages de profils (édition)
Virtual-Royaume/Royaume-Frontend pull request #48
Opened 2023-06-18 14:20 UTC by Steellgold

- [ ] Page d'édition profil
- [ ] Page d'ajout de projets
- [ ] Page d'ajout d'articles (#44)
- [ ] Page paramètres du compte
- [ ] Gérer les liens sociaux
- [ ] Messagerie
  - [ ] Envoi de message
  - [ ] Boite de réception
  - [X] Messages récents

2023-06-18 14:38 UTC, Bluzzi commented
Avant de continuer à dev dans le vide, tu devrais prendre en compte les commentaires de Romain. Je ne laisserais pas une PR passé si ça convient pas à la majorité et suite à ma discussion avec Romain hier je suis plutôt de son avis sur les besoins qu'on a pour le panel.

2023-06-19 09:23 UTC, Bluzzi requested changes

2023-06-19 09:23 UTC, Bluzzi commented on src/app/user/layout.tsx
> +import clsx from "clsx";
`import { clsx }` à la place de `import clsx`

2023-06-19 09:23 UTC, Bluzzi commented on src/app/user/links/page.tsx
> +"use client";
Pourquoi ?

2023-06-19 09:23 UTC, Bluzzi commented on src/app/user/page.tsx
> +"use client";
Pourquoi ?

2023-06-19 09:23 UTC, Bluzzi commented on src/app/user/projects/page.tsx
> +"use client";
Pourquoi ?

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/dropdown/profile/dropdown-button.tsx
> +        className ?? ""
Pas besoin de ``?? ""`

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/dropdown/profile/dropdown-link.tsx
> +      className ?? ""
Pareil

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/dropdown/profile/dropdown-separator.tsx
> +        <hr className={`w-[70%] border-t-white-desc border-opacity-10 ${className ?? ""}`} />
Pas de valeur dynamique avec Tailwind, tu le sais en plus. 

Utilise `clsx` à la place de `?? ""`

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/dropdown/profile/dropdown.type.ts
> +
Utilise `ComponentWithoutRef<"a">` et `ComponentWithoutRef<"button">` à la place de `PropsWithChildren & ButtonHTMLAttributes<HTMLButtonElement>`.

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/dropdown/profile/dropdown.type.ts
> +  className?: string;
J'aime pas trop cette façon de faire, généralement il est préférable d'étendre un composant vanilla complet.

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/texts/text.tsx
> +import clsx from "clsx";
Pas de default import

2023-06-19 09:23 UTC, Bluzzi commented on src/lib/components/atoms/texts/text.type.tsx
> +export type TextProps = HTMLAttributes<HTMLParagraphElement> & PropsWithChildren;
Pareil ici utilise `ComponentWithoutRef`

2023-06-19 19:52 UTC, Steellgold commented on src/lib/components/atoms/dropdown/profile/dropdown.type.ts
> +  className?: string;
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/48/commits/79c9c96c5c630825c798dd02b4e3932ebeddf820

2023-06-19 19:53 UTC, Steellgold commented on src/lib/components/atoms/dropdown/profile/dropdown.type.ts
> +
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/48/commits/79c9c96c5c630825c798dd02b4e3932ebeddf820

2023-06-19 19:53 UTC, Steellgold commented on src/lib/components/atoms/dropdown/profile/dropdown-separator.tsx
> +        <hr className={`w-[70%] border-t-white-desc border-opacity-10 ${className ?? ""}`} />
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/48/commits/79c9c96c5c630825c798dd02b4e3932ebeddf820

2023-06-19 19:53 UTC, Steellgold commented on src/lib/components/atoms/dropdown/profile/dropdown-link.tsx
> +      className ?? ""
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/48/commits/79c9c96c5c630825c798dd02b4e3932ebeddf820

2023-06-19 19:53 UTC, Steellgold commented on src/lib/components/atoms/dropdown/profile/dropdown-button.tsx
> +        className ?? ""
https://github.com/Virtual-Royaume/Royaume-Frontend/pull/48/commits/79c9c96c5c630825c798dd02b4e3932ebeddf820

2023-06-24 19:52 UTC, closed without merging