Ajouts de composants `form`
Virtual-Royaume/Royaume-Frontend pull request #54
Opened 2023-06-19 21:54 UTC by RomainSav

Les composants sont fait avec la possibilité de les utiliser avec `zod` et `react-hook-form`.

2023-06-21 20:46 UTC, Bluzzi requested changes
- [x] ajout de placeholder dans les exemples Storybook
- [ ] ajout du support des icons sur les inputs 
- [x] mettre tout les composants (même autre que input) au même niveau
- [x] renommer "little-navbar" en "tabs"
- [ ] création d'une card en atom avec deux variants (vu en voc)
- [x] "members-galery" à déplacer en dans le repertoire `app`
- [ ] ajouter un petit effet hover sur le bouton

2023-06-21 20:47 UTC, Bluzzi commented
Ajout de test unitaire pour les composants de formulaire aussi ? :p

2023-06-23 22:29 UTC, Steellgold commented
@RomainSav Pense tu que cela serait possible d'ajouter un paramètre à l'input "Title" qui afficherait un texte pour par exemple la section des liens afficher l'URL basique ?

[Exemple venant de Bootstrap](https://getbootstrap.com/docs/5.3/forms/input-group/#basic-example)

![image](https://github.com/Virtual-Royaume/Royaume-Frontend/assets/51505384/f7d22c38-3245-42c1-9edd-37a07cd9e94b)

2023-06-23 23:21 UTC, Bluzzi approved these changes
Pour l'instant tout me semble correct / follow ce qu'on avait vu en vocal. Je ferais un passage dans la semaine sur le design système pour finir de review le dossier `lib`, ensuite je passerais sur le dossier `app`.

2023-06-23 23:22 UTC, Bluzzi commented
Tu peux merge quand ça te semble ok @RomainSav

2023-06-24 10:56 UTC, merged